CREATE TABLE Publishers (
   id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
   Publisher VARCHAR(200)
);

CREATE TABLE Genres (
   id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
   Genre VARCHAR(200)
);

CREATE TABLE Games (
   id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
   Rank INTEGER,
   Name VARCHAR(200),
   Platform VARCHAR(200),
   Year YEAR,
   NA_Sales VARCHAR(200),
   EU_Sales VARCHAR(200),
   JP_Sales VARCHAR(200),
   Other_Sales VARCHAR(200),
   Global_Sales VARCHAR(200)
);

CREATE TABLE PublishersOfGames (
   Publisher_id INTEGER NOT NULL,
   Game_id INTEGER NOT NULL
);

CREATE TABLE GenresOfGames (
   Genre_id INTEGER NOT NULL,
   Game_id INTEGER NOT NULL
);

